# Generated by Django 5.0.1 on 2024-03-16 07:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KisumuCentralWards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.FloatField()),
                ('level', models.CharField(max_length=4)),
                ('shapename', models.CharField(max_length=33)),
                ('shapeid', models.CharField(max_length=26)),
                ('shapegroup', models.CharField(max_length=3)),
                ('shapetype', models.CharField(max_length=4)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'KisumuCentralWards',
            },
        ),
        migrations.CreateModel(
            name='OutageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=255, verbose_name='Full Name')),
                ('id_number', models.CharField(default='', max_length=50, verbose_name='ID Number')),
                ('email', models.EmailField(default='', max_length=255, verbose_name='Email')),
                ('phone_number', models.CharField(default='', max_length=20, verbose_name='Phone Number')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('description', models.TextField(verbose_name='Description')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='Outages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Outages',
            },
        ),
    ]
